language: go

go:
  - 1.10.x
  - 1.11.x

script:
  - export GO111MODULE=on
  - go test ./...
  - for i in _examples/*/; do go build $i/*.go || exit 1; done
  - >
    go_version=$(go version);
    if [ ${go_version:13:4} = "1.11" ]; then
      go get -u golang.org/x/tools/cmd/goimports;
      goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :;
    fi
